"""empty message

Revision ID: 00039b76911f
Revises: 15d220cda984
Create Date: 2017-09-20 22:00:19.375686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00039b76911f'
down_revision = '15d220cda984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_member_user_id', table_name='sg_member')
    op.drop_index('member_sg_index', table_name='sg_member')
    op.drop_constraint(u'sg_member_user_id_fkey', 'sg_member', type_='foreignkey')
    op.drop_column('sg_member', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sg_member_user_id_fkey', 'sg_member', 'users', ['user_id'], ['id'])
    op.create_index('member_sg_index', 'sg_member', ['saving_group_id', 'user_id'], unique=True)
    op.create_index('ix_sg_member_user_id', 'sg_member', ['user_id'], unique=False)
    # ### end Alembic commands ###
