"""empty message

Revision ID: 002dba70db49
Revises: 637cb6d2c4c2
Create Date: 2017-09-24 22:00:34.410125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002dba70db49'
down_revision = '637cb6d2c4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_fine', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
