"""empty message

Revision ID: 03340bb199f3
Revises: 2bf9603a2e66
Create Date: 2017-09-20 21:51:44.165394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03340bb199f3'
down_revision = '2bf9603a2e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_secondary_phone_key', 'users', type_='unique')
    op.drop_column('users', 'secondary_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secondary_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'users_secondary_phone_key', 'users', ['secondary_phone'])
    # ### end Alembic commands ###
