"""empty message

Revision ID: 03dc3ba21822
Revises: 85f709b5c340
Create Date: 2017-11-28 11:25:32.046254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03dc3ba21822'
down_revision = '85f709b5c340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sg_share_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_amount', sa.Float(), nullable=True),
    sa.Column('reinvested_amount', sa.Float(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['sg_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_share_out_cycle_id'), 'sg_share_out', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sg_share_out_cycle_id'), table_name='sg_share_out')
    op.drop_table('sg_share_out')
    # ### end Alembic commands ###
