"""empty message

Revision ID: 040bce0743f2
Revises: 5f0c2d99d648
Create Date: 2017-12-18 12:52:36.051438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040bce0743f2'
down_revision = '5f0c2d99d648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_share_out', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_share_out', 'create_at')
    # ### end Alembic commands ###
