"""empty message

Revision ID: 045ee29ed26f
Revises: d93e2e4a8a3d
Create Date: 2017-11-25 16:21:47.903561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045ee29ed26f'
down_revision = 'd93e2e4a8a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('payment_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_loan', 'payment_type')
    # ### end Alembic commands ###
