"""empty message

Revision ID: 04c08b9dcee6
Revises: 42dd23a186cc
Create Date: 2017-12-24 14:49:42.647252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c08b9dcee6'
down_revision = '42dd23a186cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('drop_out_cycle', 'sg_drop_out', ['sg_cycle_id', 'member_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('drop_out_cycle', table_name='sg_drop_out')
    # ### end Alembic commands ###
