"""empty message

Revision ID: 06e6b0c847f6
Revises: ec1cd32ef1fd
Create Date: 2017-09-07 22:10:42.815311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e6b0c847f6'
down_revision = 'ec1cd32ef1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('debit_loan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_approved_loan_debit_loan_id'), 'member_approved_loan', ['debit_loan_id'], unique=False)
    op.create_foreign_key(None, 'member_approved_loan', 'member_loan', ['debit_loan_id'], ['id'])
    op.add_column('member_approved_social', sa.Column('social_debit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_approved_social_social_debit_id'), 'member_approved_social', ['social_debit_id'], unique=False)
    op.create_foreign_key(None, 'member_approved_social', 'member_social_fund', ['social_debit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_approved_social', type_='foreignkey')
    op.drop_index(op.f('ix_member_approved_social_social_debit_id'), table_name='member_approved_social')
    op.drop_column('member_approved_social', 'social_debit_id')
    op.drop_constraint(None, 'member_approved_loan', type_='foreignkey')
    op.drop_index(op.f('ix_member_approved_loan_debit_loan_id'), table_name='member_approved_loan')
    op.drop_column('member_approved_loan', 'debit_loan_id')
    # ### end Alembic commands ###
