"""empty message

Revision ID: 06eb053bab8c
Revises: 30b2a19cebdd
Create Date: 2017-09-19 16:19:52.011923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eb053bab8c'
down_revision = '30b2a19cebdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_wallet_saving_group_id', table_name='sg_wallet')
    op.create_index(op.f('ix_sg_wallet_saving_group_id'), 'sg_wallet', ['saving_group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sg_wallet_saving_group_id'), table_name='sg_wallet')
    op.create_index('ix_sg_wallet_saving_group_id', 'sg_wallet', ['saving_group_id'], unique=False)
    # ### end Alembic commands ###
