"""empty message

Revision ID: 088c5c66de80
Revises: 
Create Date: 2017-09-07 22:08:41.069490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '088c5c66de80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_loaned', sa.Float(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('amount_to_pay', sa.Float(), nullable=True),
    sa.Column('date_repayment', sa.Date(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_loan_sg_cycle_id'), 'member_loan', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_member_loan_sg_member_id'), 'member_loan', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_member_loan_sg_wallet_id'), 'member_loan', ['sg_wallet_id'], unique=False)
    op.create_table('member_social_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_debited', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_social_fund_sg_cycle_id'), 'member_social_fund', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_member_social_fund_sg_member_id'), 'member_social_fund', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_member_social_fund_sg_wallet_id'), 'member_social_fund', ['sg_wallet_id'], unique=False)
    op.create_table('member_approved_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('debit_loan_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['debit_loan_id'], ['member_loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_approved_loan_committee_id'), 'member_approved_loan', ['committee_id'], unique=False)
    op.create_index(op.f('ix_member_approved_loan_debit_loan_id'), 'member_approved_loan', ['debit_loan_id'], unique=False)
    op.create_table('member_approved_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('social_debit_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['social_debit_id'], ['member_social_fund.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_approved_social_committee_id'), 'member_approved_social', ['committee_id'], unique=False)
    op.create_index(op.f('ix_member_approved_social_social_debit_id'), 'member_approved_social', ['social_debit_id'], unique=False)
    op.drop_table('sg_social_debit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sg_social_debit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount_debited', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sg_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_wallet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], [u'sg_cycle.id'], name=u'sg_social_debit_sg_cycle_id_fkey'),
    sa.ForeignKeyConstraint(['sg_member_id'], [u'sg_member.id'], name=u'sg_social_debit_sg_member_id_fkey'),
    sa.ForeignKeyConstraint(['sg_wallet_id'], [u'sg_wallet.id'], name=u'sg_social_debit_sg_wallet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'sg_social_debit_pkey')
    )
    op.drop_index(op.f('ix_member_approved_social_social_debit_id'), table_name='member_approved_social')
    op.drop_index(op.f('ix_member_approved_social_committee_id'), table_name='member_approved_social')
    op.drop_table('member_approved_social')
    op.drop_index(op.f('ix_member_approved_loan_debit_loan_id'), table_name='member_approved_loan')
    op.drop_index(op.f('ix_member_approved_loan_committee_id'), table_name='member_approved_loan')
    op.drop_table('member_approved_loan')
    op.drop_index(op.f('ix_member_social_fund_sg_wallet_id'), table_name='member_social_fund')
    op.drop_index(op.f('ix_member_social_fund_sg_member_id'), table_name='member_social_fund')
    op.drop_index(op.f('ix_member_social_fund_sg_cycle_id'), table_name='member_social_fund')
    op.drop_table('member_social_fund')
    op.drop_index(op.f('ix_member_loan_sg_wallet_id'), table_name='member_loan')
    op.drop_index(op.f('ix_member_loan_sg_member_id'), table_name='member_loan')
    op.drop_index(op.f('ix_member_loan_sg_cycle_id'), table_name='member_loan')
    op.drop_table('member_loan')
    # ### end Alembic commands ###
