"""empty message

Revision ID: 0960f8ff0620
Revises: 7706f1ab4107
Create Date: 2017-11-20 13:07:54.004923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0960f8ff0620'
down_revision = '7706f1ab4107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_fine_sg_cycle', table_name='member_fine')
    op.drop_constraint(u'member_fine_sg_cycle_fkey', 'member_fine', type_='foreignkey')
    op.drop_column('member_fine', 'sg_cycle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('sg_cycle', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_fine_sg_cycle_fkey', 'member_fine', 'sg_cycle', ['sg_cycle'], ['id'])
    op.create_index('ix_member_fine_sg_cycle', 'member_fine', ['sg_cycle'], unique=False)
    # ### end Alembic commands ###
