"""empty message

Revision ID: 0993e072ea55
Revises: 5595c0190f82
Create Date: 2017-12-12 19:35:34.975752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0993e072ea55'
down_revision = '5595c0190f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_partner_id'), 'users', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_partner_id'), table_name='users')
    op.drop_column('users', 'partner_id')
    # ### end Alembic commands ###
