"""empty message

Revision ID: 11d48e7e82dc
Revises: 856118a6790d
Create Date: 2017-09-11 16:11:08.104807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d48e7e82dc'
down_revision = '856118a6790d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_approved_loan_sg_member_id', table_name='member_approved_loan')
    op.drop_constraint(u'member_approved_loan_sg_member_id_fkey', 'member_approved_loan', type_='foreignkey')
    op.drop_column('member_approved_loan', 'sg_member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_approved_loan_sg_member_id_fkey', 'member_approved_loan', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_member_approved_loan_sg_member_id', 'member_approved_loan', ['sg_member_id'], unique=False)
    # ### end Alembic commands ###
