"""empty message

Revision ID: 15d220cda984
Revises: 03340bb199f3
Create Date: 2017-09-20 21:54:23.723217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d220cda984'
down_revision = '03340bb199f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secondary_phone', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'users', ['secondary_phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'secondary_phone')
    # ### end Alembic commands ###
