"""empty message

Revision ID: 1601f902c43c
Revises: 496c7f242f17
Create Date: 2017-11-27 14:30:37.741040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1601f902c43c'
down_revision = '496c7f242f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('activate', sa.Integer(), nullable=True))
    op.add_column('sg_member', sa.Column('drop_cycle_id', sa.Integer(), nullable=True))
    op.add_column('sg_member', sa.Column('sg_cycle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_member_drop_cycle_id'), 'sg_member', ['drop_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_member_sg_cycle_id'), 'sg_member', ['sg_cycle_id'], unique=False)
    op.create_foreign_key(None, 'sg_member', 'sg_cycle', ['sg_cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_member', type_='foreignkey')
    op.drop_index(op.f('ix_sg_member_sg_cycle_id'), table_name='sg_member')
    op.drop_index(op.f('ix_sg_member_drop_cycle_id'), table_name='sg_member')
    op.drop_column('sg_member', 'sg_cycle_id')
    op.drop_column('sg_member', 'drop_cycle_id')
    op.drop_column('sg_member', 'activate')
    # ### end Alembic commands ###
