"""empty message

Revision ID: 16c1ce0a496e
Revises: 703a659da5c6
Create Date: 2017-09-18 17:23:37.474744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c1ce0a496e'
down_revision = '703a659da5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_social', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('member_approved_social', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('member_approved_social', sa.Column('status_date', sa.DateTime(), nullable=True))
    op.drop_column('member_approved_social', 'approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_social', sa.Column('approved', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('member_approved_social', 'status_date')
    op.drop_column('member_approved_social', 'status')
    op.drop_column('member_approved_social', 'date')
    # ### end Alembic commands ###
