"""empty message

Revision ID: 177f5ae1f8eb
Revises: a6e516c9ef8e
Create Date: 2017-08-22 13:08:13.550781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177f5ae1f8eb'
down_revision = 'a6e516c9ef8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intervention_area_user_id', table_name='intervention_area')
    op.drop_constraint(u'intervention_area_user_id_fkey', 'intervention_area', type_='foreignkey')
    op.drop_column('intervention_area', 'user_id')
    op.create_unique_constraint(None, 'village', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'village', type_='unique')
    op.add_column('intervention_area', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'intervention_area_user_id_fkey', 'intervention_area', 'users', ['user_id'], ['id'])
    op.create_index('ix_intervention_area_user_id', 'intervention_area', ['user_id'], unique=False)
    # ### end Alembic commands ###
