"""empty message

Revision ID: 1d72c62d6f3a
Revises: def50d3996d6
Create Date: 2017-08-31 11:09:41.927472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d72c62d6f3a'
down_revision = 'def50d3996d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('saving_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_member_saving_group_id'), 'sg_member', ['saving_group_id'], unique=False)
    op.create_foreign_key(None, 'sg_member', 'saving_group', ['saving_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_member', type_='foreignkey')
    op.drop_index(op.f('ix_sg_member_saving_group_id'), table_name='sg_member')
    op.drop_column('sg_member', 'saving_group_id')
    # ### end Alembic commands ###
