"""empty message

Revision ID: 1ee925d10bbb
Revises: 1d72c62d6f3a
Create Date: 2017-08-31 11:13:50.785724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee925d10bbb'
down_revision = '1d72c62d6f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('member_sg_index', 'sg_member', ['saving_group_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('member_sg_index', table_name='sg_member')
    # ### end Alembic commands ###
