"""empty message

Revision ID: 26681c1d32ce
Revises: 1ee925d10bbb
Create Date: 2017-09-04 10:41:19.691622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26681c1d32ce'
down_revision = '1ee925d10bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('pin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_member', 'pin')
    # ### end Alembic commands ###
