"""empty message

Revision ID: 2860043d3fcd
Revises: d26c672fb6aa
Create Date: 2018-01-05 17:06:44.379638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2860043d3fcd'
down_revision = 'd26c672fb6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine_repayment', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('member_fine_repayment', sa.Column('member_fine_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_fine_repayment_member_fine_id'), 'member_fine_repayment', ['member_fine_id'], unique=False)
    op.drop_index('ix_member_fine_repayment_loan_id', table_name='member_fine_repayment')
    op.drop_constraint(u'member_fine_repayment_loan_id_fkey', 'member_fine_repayment', type_='foreignkey')
    op.create_foreign_key(None, 'member_fine_repayment', 'member_fine', ['member_fine_id'], ['id'])
    op.drop_column('member_fine_repayment', 'date')
    op.drop_column('member_fine_repayment', 'loan_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine_repayment', sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_fine_repayment', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_fine_repayment', type_='foreignkey')
    op.create_foreign_key(u'member_fine_repayment_loan_id_fkey', 'member_fine_repayment', 'member_loan', ['loan_id'], ['id'])
    op.create_index('ix_member_fine_repayment_loan_id', 'member_fine_repayment', ['loan_id'], unique=False)
    op.drop_index(op.f('ix_member_fine_repayment_member_fine_id'), table_name='member_fine_repayment')
    op.drop_column('member_fine_repayment', 'member_fine_id')
    op.drop_column('member_fine_repayment', 'create_at')
    # ### end Alembic commands ###
