"""empty message

Revision ID: 2bf9603a2e66
Revises: 06eb053bab8c
Create Date: 2017-09-20 13:02:48.695008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf9603a2e66'
down_revision = '06eb053bab8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.drop_index('project_agent_index', table_name='project_agent')
    op.add_column('saving_group', sa.Column('loan_fine', sa.Integer(), nullable=True))
    op.add_column('saving_group', sa.Column('meeting_absence', sa.Integer(), nullable=True))
    op.add_column('saving_group', sa.Column('saving_fine', sa.Integer(), nullable=True))
    op.add_column('saving_group', sa.Column('social_fund_fine', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_group', 'social_fund_fine')
    op.drop_column('saving_group', 'saving_fine')
    op.drop_column('saving_group', 'meeting_absence')
    op.drop_column('saving_group', 'loan_fine')
    op.create_index('project_agent_index', 'project_agent', ['project_id', 'user_id'], unique=True)
    op.drop_column('project', 'partner_id')
    # ### end Alembic commands ###
