"""empty message

Revision ID: 2e8f5718ff7e
Revises: fc219b8e064f
Create Date: 2017-08-09 15:23:35.284304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8f5718ff7e'
down_revision = 'fc219b8e064f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'date')
    # ### end Alembic commands ###
