"""empty message

Revision ID: 2fb973ea5b6a
Revises: 3fa1740d4bc0
Create Date: 2017-08-13 21:52:33.334916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb973ea5b6a'
down_revision = '3fa1740d4bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention_area', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervention_area', 'date')
    # ### end Alembic commands ###
