"""empty message

Revision ID: 30f6cf1b46e8
Revises: cabb0df3988a
Create Date: 2017-12-11 19:51:28.307680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f6cf1b46e8'
down_revision = 'cabb0df3988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
