"""empty message

Revision ID: 3497d3f0a753
Revises: 5cd4e5105dac
Create Date: 2017-08-22 15:31:41.791126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3497d3f0a753'
down_revision = '5cd4e5105dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_agent', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_agent_user_id'), 'project_agent', ['user_id'], unique=False)
    op.drop_index('ix_project_agent_agent_id', table_name='project_agent')
    op.drop_constraint(u'project_agent_agent_id_fkey', 'project_agent', type_='foreignkey')
    op.create_foreign_key(None, 'project_agent', 'users', ['user_id'], ['id'])
    op.drop_column('project_agent', 'agent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_agent', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_agent', type_='foreignkey')
    op.create_foreign_key(u'project_agent_agent_id_fkey', 'project_agent', 'users', ['agent_id'], ['id'])
    op.create_index('ix_project_agent_agent_id', 'project_agent', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_project_agent_user_id'), table_name='project_agent')
    op.drop_column('project_agent', 'user_id')
    # ### end Alembic commands ###
