"""empty message

Revision ID: 3f9d5975c270
Revises: 2860043d3fcd
Create Date: 2018-01-07 16:22:52.533261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9d5975c270'
down_revision = '2860043d3fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_intervention_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('project_agent_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_agent_id'], ['project_agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_intervention_area_project_agent_id'), 'agent_intervention_area', ['project_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_intervention_area_village_id'), 'agent_intervention_area', ['village_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_intervention_area_village_id'), table_name='agent_intervention_area')
    op.drop_index(op.f('ix_agent_intervention_area_project_agent_id'), table_name='agent_intervention_area')
    op.drop_table('agent_intervention_area')
    # ### end Alembic commands ###
