"""empty message

Revision ID: 3fa1740d4bc0
Revises: 2e8f5718ff7e
Create Date: 2017-08-09 17:20:46.464989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa1740d4bc0'
down_revision = '2e8f5718ff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_area_project_id'), 'intervention_area', ['project_id'], unique=False)
    op.create_index(op.f('ix_intervention_area_user_id'), 'intervention_area', ['user_id'], unique=False)
    op.create_index(op.f('ix_intervention_area_village_id'), 'intervention_area', ['village_id'], unique=False)
    op.drop_table('project_intervention_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_intervention_area',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'project_intervention_area_pkey')
    )
    op.drop_index(op.f('ix_intervention_area_village_id'), table_name='intervention_area')
    op.drop_index(op.f('ix_intervention_area_user_id'), table_name='intervention_area')
    op.drop_index(op.f('ix_intervention_area_project_id'), table_name='intervention_area')
    op.drop_table('intervention_area')
    op.drop_table('village')
    # ### end Alembic commands ###
