"""empty message

Revision ID: 42dd23a186cc
Revises: ed2178f487c8
Create Date: 2017-12-24 14:30:20.761222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dd23a186cc'
down_revision = 'ed2178f487c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_out_approved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('status_at', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('drop_out_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['drop_out_id'], ['sg_drop_out.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_out_approved_admin_id'), 'drop_out_approved', ['admin_id'], unique=False)
    op.create_index(op.f('ix_drop_out_approved_drop_out_id'), 'drop_out_approved', ['drop_out_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drop_out_approved_drop_out_id'), table_name='drop_out_approved')
    op.drop_index(op.f('ix_drop_out_approved_admin_id'), table_name='drop_out_approved')
    op.drop_table('drop_out_approved')
    # ### end Alembic commands ###
