"""empty message

Revision ID: 42eccb7328c3
Revises: 97bd35190d6a
Create Date: 2017-10-18 20:06:59.430907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42eccb7328c3'
down_revision = '97bd35190d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_number', sa.String(length=60), nullable=True))
    op.drop_constraint(u'users_secondary_phone_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id_number'])
    op.drop_column('users', 'secondary_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secondary_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_secondary_phone_key', 'users', ['secondary_phone'])
    op.drop_column('users', 'id_number')
    # ### end Alembic commands ###
