"""empty message

Revision ID: 45cfca8c713b
Revises: 8cee2fade7b1
Create Date: 2017-09-07 23:11:34.866180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cfca8c713b'
down_revision = '8cee2fade7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('date_repayment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_loan', 'date_repayment')
    # ### end Alembic commands ###
