"""empty message

Revision ID: 45e86735e146
Revises: 26681c1d32ce
Create Date: 2017-09-04 11:36:20.229067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e86735e146'
down_revision = '26681c1d32ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_member', 'pin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('pin', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
