"""empty message

Revision ID: 496c7f242f17
Revises: 045ee29ed26f
Create Date: 2017-11-26 17:01:00.233639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496c7f242f17'
down_revision = '045ee29ed26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('write_off_admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_loan', 'write_off_admin')
    # ### end Alembic commands ###
