"""empty message

Revision ID: 4d4ce1fefdcf
Revises: f635efb380b5
Create Date: 2017-09-25 11:26:00.818282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4ce1fefdcf'
down_revision = 'f635efb380b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_share', 'saving_group_shares', ['saving_group_id', 'sg_cycle_id'], unique=True)
    op.create_index('unique_fine', 'sg_fines', ['saving_group_id', 'sg_cycle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_fine', table_name='sg_fines')
    op.drop_index('unique_share', table_name='saving_group_shares')
    # ### end Alembic commands ###
