"""empty message

Revision ID: 4dc89268568c
Revises: 
Create Date: 2017-09-07 21:38:52.032880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc89268568c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sg_debit_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_loaned', sa.Float(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('amount_to_pay', sa.Float(), nullable=True),
    sa.Column('date_repayment', sa.Date(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_debit_loan_sg_cycle_id'), 'sg_debit_loan', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_debit_loan_sg_member_id'), 'sg_debit_loan', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_sg_debit_loan_sg_wallet_id'), 'sg_debit_loan', ['sg_wallet_id'], unique=False)
    op.create_table('sg_approved_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('debit_loan_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['debit_loan_id'], ['sg_debit_loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_approved_loan_committee_id'), 'sg_approved_loan', ['committee_id'], unique=False)
    op.create_index(op.f('ix_sg_approved_loan_debit_loan_id'), 'sg_approved_loan', ['debit_loan_id'], unique=False)
    op.create_table('sg_approved_social_debit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('social_debit_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['social_debit_id'], ['sg_social_debit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_approved_social_debit_committee_id'), 'sg_approved_social_debit', ['committee_id'], unique=False)
    op.create_index(op.f('ix_sg_approved_social_debit_social_debit_id'), 'sg_approved_social_debit', ['social_debit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sg_approved_social_debit_social_debit_id'), table_name='sg_approved_social_debit')
    op.drop_index(op.f('ix_sg_approved_social_debit_committee_id'), table_name='sg_approved_social_debit')
    op.drop_table('sg_approved_social_debit')
    op.drop_index(op.f('ix_sg_approved_loan_debit_loan_id'), table_name='sg_approved_loan')
    op.drop_index(op.f('ix_sg_approved_loan_committee_id'), table_name='sg_approved_loan')
    op.drop_table('sg_approved_loan')
    op.drop_index(op.f('ix_sg_debit_loan_sg_wallet_id'), table_name='sg_debit_loan')
    op.drop_index(op.f('ix_sg_debit_loan_sg_member_id'), table_name='sg_debit_loan')
    op.drop_index(op.f('ix_sg_debit_loan_sg_cycle_id'), table_name='sg_debit_loan')
    op.drop_table('sg_debit_loan')
    # ### end Alembic commands ###
