"""empty message

Revision ID: 5595c0190f82
Revises: 30f6cf1b46e8
Create Date: 2017-12-11 20:24:34.442902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5595c0190f82'
down_revision = '30f6cf1b46e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intervention_area_village_id', table_name='intervention_area')
    op.drop_constraint(u'intervention_area_village_id_fkey', 'intervention_area', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'intervention_area_village_id_fkey', 'intervention_area', 'village', ['village_id'], ['id'])
    op.create_index('ix_intervention_area_village_id', 'intervention_area', ['village_id'], unique=False)
    # ### end Alembic commands ###
