"""empty message

Revision ID: 5c5ee9e52fea
Revises: 61402df04d14
Create Date: 2017-11-20 15:43:14.799024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5ee9e52fea'
down_revision = '61402df04d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_fines', sa.Column('acronym', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_fines', 'acronym')
    # ### end Alembic commands ###
