"""empty message

Revision ID: 5cd4e5105dac
Revises: 177f5ae1f8eb
Create Date: 2017-08-22 15:08:56.018877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd4e5105dac'
down_revision = '177f5ae1f8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_agent_agent_id'), 'project_agent', ['agent_id'], unique=False)
    op.create_index(op.f('ix_project_agent_project_id'), 'project_agent', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_agent_project_id'), table_name='project_agent')
    op.drop_index(op.f('ix_project_agent_agent_id'), table_name='project_agent')
    op.drop_table('project_agent')
    # ### end Alembic commands ###
