"""empty message

Revision ID: 5db7cecdc467
Revises: 4d4ce1fefdcf
Create Date: 2017-10-03 15:10:37.969498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db7cecdc467'
down_revision = '4d4ce1fefdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_approved_social_sg_member_id', table_name='member_approved_social')
    op.drop_constraint(u'member_approved_social_sg_member_id_fkey', 'member_approved_social', type_='foreignkey')
    op.drop_column('member_approved_social', 'sg_member_id')
    op.drop_index('ix_member_fine_member_id', table_name='member_fine')
    op.drop_constraint(u'member_fine_member_id_fkey', 'member_fine', type_='foreignkey')
    op.drop_column('member_fine', 'member_id')
    op.drop_index('ix_member_social_fund_sg_member_id', table_name='member_social_fund')
    op.drop_constraint(u'member_social_fund_sg_member_id_fkey', 'member_social_fund', type_='foreignkey')
    op.drop_column('member_social_fund', 'sg_member_id')
    op.drop_index('ix_sg_member_contributions_sg_member_id', table_name='sg_member_contributions')
    op.drop_constraint(u'sg_member_contributions_sg_member_id_fkey', 'sg_member_contributions', type_='foreignkey')
    op.drop_column('sg_member_contributions', 'sg_member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member_contributions', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sg_member_contributions_sg_member_id_fkey', 'sg_member_contributions', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_sg_member_contributions_sg_member_id', 'sg_member_contributions', ['sg_member_id'], unique=False)
    op.add_column('member_social_fund', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_social_fund_sg_member_id_fkey', 'member_social_fund', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_member_social_fund_sg_member_id', 'member_social_fund', ['sg_member_id'], unique=False)
    op.add_column('member_fine', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_fine_member_id_fkey', 'member_fine', 'sg_member', ['member_id'], ['id'])
    op.create_index('ix_member_fine_member_id', 'member_fine', ['member_id'], unique=False)
    op.add_column('member_approved_social', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_approved_social_sg_member_id_fkey', 'member_approved_social', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_member_approved_social_sg_member_id', 'member_approved_social', ['sg_member_id'], unique=False)
    # ### end Alembic commands ###
