"""empty message

Revision ID: 5e11b47d31da
Revises: 19641592eaf9
Create Date: 2017-09-04 12:03:23.465037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e11b47d31da'
down_revision = '19641592eaf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_member_pin', table_name='sg_member')
    op.drop_column('sg_member', 'pin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('pin', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.create_index('ix_sg_member_pin', 'sg_member', ['pin'], unique=False)
    # ### end Alembic commands ###
