"""empty message

Revision ID: 5f0c2d99d648
Revises: c3f396094041
Create Date: 2017-12-18 11:44:58.385158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0c2d99d648'
down_revision = 'c3f396094041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['sg_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_cycle_cycle_id'), 'member_cycle', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_member_cycle_member_id'), 'member_cycle', ['member_id'], unique=False)
    op.drop_index('ix_sg_member_sg_cycle_id', table_name='sg_member')
    op.drop_constraint(u'sg_member_sg_cycle_id_fkey', 'sg_member', type_='foreignkey')
    op.drop_column(u'sg_member', 'sg_cycle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sg_member', sa.Column('sg_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sg_member_sg_cycle_id_fkey', 'sg_member', 'sg_cycle', ['sg_cycle_id'], ['id'])
    op.create_index('ix_sg_member_sg_cycle_id', 'sg_member', ['sg_cycle_id'], unique=False)
    op.drop_index(op.f('ix_member_cycle_member_id'), table_name='member_cycle')
    op.drop_index(op.f('ix_member_cycle_cycle_id'), table_name='member_cycle')
    op.drop_table('member_cycle')
    # ### end Alembic commands ###
