"""empty message

Revision ID: 61402df04d14
Revises: 0960f8ff0620
Create Date: 2017-11-20 13:18:14.668116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61402df04d14'
down_revision = '0960f8ff0620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_fine', table_name='sg_fines')
    op.create_index('unique_fine', 'sg_fines', ['saving_group_id', 'sg_cycle_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_fine', table_name='sg_fines')
    op.create_index('unique_fine', 'sg_fines', ['saving_group_id', 'sg_cycle_id'], unique=True)
    # ### end Alembic commands ###
