"""empty message

Revision ID: 61ca6502db98
Revises: ddf1dfecc4be
Create Date: 2017-09-04 18:17:42.840666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca6502db98'
down_revision = 'ddf1dfecc4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_member_contributions_sg_cycle_id', table_name='sg_member_contributions')
    op.drop_constraint(u'sg_member_contributions_sg_cycle_id_fkey', 'sg_member_contributions', type_='foreignkey')
    op.drop_column('sg_member_contributions', 'sg_cycle_id')
    op.add_column('sg_wallet', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_wallet', 'date')
    op.add_column('sg_member_contributions', sa.Column('sg_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sg_member_contributions_sg_cycle_id_fkey', 'sg_member_contributions', 'sg_cycle', ['sg_cycle_id'], ['id'])
    op.create_index('ix_sg_member_contributions_sg_cycle_id', 'sg_member_contributions', ['sg_cycle_id'], unique=False)
    # ### end Alembic commands ###
