"""empty message

Revision ID: 6284e780abb4
Revises: b8d0b19e9445
Create Date: 2018-01-02 21:31:57.948640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6284e780abb4'
down_revision = 'b8d0b19e9445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_share_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=30), nullable=True),
    sa.Column('operator_transaction_id', sa.String(length=30), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('share_out_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['share_out_id'], ['sg_share_out.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id'),
    sa.UniqueConstraint('operator_transaction_id')
    )
    op.create_index(op.f('ix_member_share_out_member_id'), 'member_share_out', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_share_out_share_out_id'), 'member_share_out', ['share_out_id'], unique=False)
    op.add_column(u'sg_share_out', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sg_share_out', 'status')
    op.drop_index(op.f('ix_member_share_out_share_out_id'), table_name='member_share_out')
    op.drop_index(op.f('ix_member_share_out_member_id'), table_name='member_share_out')
    op.drop_table('member_share_out')
    # ### end Alembic commands ###
