"""empty message

Revision ID: 637cb6d2c4c2
Revises: 8957f86d0243
Create Date: 2017-09-24 20:11:52.506116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637cb6d2c4c2'
down_revision = '8957f86d0243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saving_group_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('max_share', sa.Integer(), nullable=True),
    sa.Column('social_fund', sa.Integer(), nullable=True),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saving_group_shares_saving_group_id'), 'saving_group_shares', ['saving_group_id'], unique=False)
    op.create_index(op.f('ix_saving_group_shares_sg_cycle_id'), 'saving_group_shares', ['sg_cycle_id'], unique=False)
    op.create_table('sg_fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('social_fund', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('loan', sa.Integer(), nullable=True),
    sa.Column('saving', sa.Integer(), nullable=True),
    sa.Column('meeting', sa.Integer(), nullable=True),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_fines_saving_group_id'), 'sg_fines', ['saving_group_id'], unique=False)
    op.create_index(op.f('ix_sg_fines_sg_cycle_id'), 'sg_fines', ['sg_cycle_id'], unique=False)
    op.drop_column(u'saving_group', 'meeting_absence')
    op.drop_column(u'saving_group', 'saving_fine')
    op.drop_column(u'saving_group', 'share')
    op.drop_column(u'saving_group', 'social_fund')
    op.drop_column(u'saving_group', 'attendance_fine')
    op.drop_column(u'saving_group', 'social_fund_fine')
    op.drop_column(u'saving_group', 'loan_fine')
    op.drop_column(u'saving_group', 'max_share')
    op.drop_column(u'saving_group', 'interest_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'saving_group', sa.Column('interest_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('max_share', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('loan_fine', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('social_fund_fine', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('attendance_fine', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('social_fund', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('share', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('saving_fine', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'saving_group', sa.Column('meeting_absence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sg_fines_sg_cycle_id'), table_name='sg_fines')
    op.drop_index(op.f('ix_sg_fines_saving_group_id'), table_name='sg_fines')
    op.drop_table('sg_fines')
    op.drop_index(op.f('ix_saving_group_shares_sg_cycle_id'), table_name='saving_group_shares')
    op.drop_index(op.f('ix_saving_group_shares_saving_group_id'), table_name='saving_group_shares')
    op.drop_table('saving_group_shares')
    # ### end Alembic commands ###
