"""empty message

Revision ID: 6a2ad52f7e77
Revises: 1601f902c43c
Create Date: 2017-11-27 16:07:59.492927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2ad52f7e77'
down_revision = '1601f902c43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_member_drop_cycle_id', table_name='sg_member')
    op.drop_column('sg_member', 'drop_cycle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('drop_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_sg_member_drop_cycle_id', 'sg_member', ['drop_cycle_id'], unique=False)
    # ### end Alembic commands ###
