"""empty message

Revision ID: 6c88fdefeadf
Revises: 11d48e7e82dc
Create Date: 2017-09-11 16:11:24.111100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c88fdefeadf'
down_revision = '11d48e7e82dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('sg_member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_approved_loan_sg_member_id'), 'member_approved_loan', ['sg_member_id'], unique=False)
    op.create_foreign_key(None, 'member_approved_loan', 'sg_member', ['sg_member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_approved_loan', type_='foreignkey')
    op.drop_index(op.f('ix_member_approved_loan_sg_member_id'), table_name='member_approved_loan')
    op.drop_column('member_approved_loan', 'sg_member_id')
    # ### end Alembic commands ###
