"""empty message

Revision ID: 6c9382fcd6ce
Revises: 45cfca8c713b
Create Date: 2017-09-07 23:27:38.556978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c9382fcd6ce'
down_revision = '45cfca8c713b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_loan', 'amount_to_pay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('amount_to_pay', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
