"""empty message

Revision ID: 703a659da5c6
Revises: f762d968c259
Create Date: 2017-09-12 11:51:19.448481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '703a659da5c6'
down_revision = 'f762d968c259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('member_approved_loan', sa.Column('status_date', sa.DateTime(), nullable=True))
    op.drop_column('member_approved_loan', 'declined_date')
    op.drop_column('member_approved_loan', 'approved')
    op.drop_column('member_approved_loan', 'approve_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('approve_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('member_approved_loan', sa.Column('approved', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_approved_loan', sa.Column('declined_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('member_approved_loan', 'status_date')
    op.drop_column('member_approved_loan', 'status')
    # ### end Alembic commands ###
