"""empty message

Revision ID: 7306b05cb99f
Revises: f81c1eda135d
Create Date: 2017-09-11 17:12:34.133737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7306b05cb99f'
down_revision = 'f81c1eda135d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_code', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmation_code')
    # ### end Alembic commands ###
