"""empty message

Revision ID: 734f9e2e2f58
Revises: 5e11b47d31da
Create Date: 2017-09-04 12:03:34.325789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734f9e2e2f58'
down_revision = '5e11b47d31da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('pin', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_sg_member_pin'), 'sg_member', ['pin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sg_member_pin'), table_name='sg_member')
    op.drop_column('sg_member', 'pin')
    # ### end Alembic commands ###
