"""empty message

Revision ID: 7706f1ab4107
Revises: dacb1dcf4663
Create Date: 2017-11-20 13:06:47.297469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7706f1ab4107'
down_revision = 'dacb1dcf4663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('sg_cycle', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_fine_sg_cycle'), 'member_fine', ['sg_cycle'], unique=False)
    op.create_foreign_key(None, 'member_fine', 'sg_cycle', ['sg_cycle'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_fine', type_='foreignkey')
    op.drop_index(op.f('ix_member_fine_sg_cycle'), table_name='member_fine')
    op.drop_column('member_fine', 'sg_cycle')
    # ### end Alembic commands ###
