"""empty message

Revision ID: 774412da8464
Revises: 9340e0f60e8f
Create Date: 2017-12-19 17:10:18.650818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774412da8464'
down_revision = '9340e0f60e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_cycle', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_cycle', 'create_at')
    # ### end Alembic commands ###
