"""empty message

Revision ID: 775ef3ef4a3d
Revises: 00039b76911f
Create Date: 2017-09-20 22:00:32.162741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775ef3ef4a3d'
down_revision = '00039b76911f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_member_user_id'), 'sg_member', ['user_id'], unique=False)
    op.create_index('member_sg_index', 'sg_member', ['saving_group_id', 'user_id'], unique=True)
    op.create_foreign_key(None, 'sg_member', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_member', type_='foreignkey')
    op.drop_index('member_sg_index', table_name='sg_member')
    op.drop_index(op.f('ix_sg_member_user_id'), table_name='sg_member')
    op.drop_column('sg_member', 'user_id')
    # ### end Alembic commands ###
