"""empty message

Revision ID: 7a0310ae7b18
Revises: 9c60dd40ae11
Create Date: 2017-08-30 22:31:15.699069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0310ae7b18'
down_revision = '9c60dd40ae11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('reg_date', sa.DateTime(), nullable=True))
    op.drop_column('saving_group', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('saving_group', 'reg_date')
    # ### end Alembic commands ###
