"""empty message

Revision ID: 7a69031a4a7d
Revises: 3f9d5975c270
Create Date: 2018-01-12 00:31:28.722421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a69031a4a7d'
down_revision = '3f9d5975c270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
