"""empty message

Revision ID: 7f1eac3d0354
Revises: e21b0ecc11e8
Create Date: 2017-12-26 06:49:38.705278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f1eac3d0354'
down_revision = 'e21b0ecc11e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_write_off')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_write_off',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], [u'sg_member.id'], name=u'member_write_off_admin_id_fkey'),
    sa.ForeignKeyConstraint(['loan_id'], [u'member_loan.id'], name=u'member_write_off_loan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'member_write_off_pkey')
    )
    # ### end Alembic commands ###
