"""empty message

Revision ID: 7fea657e6c88
Revises: c8a66ebc33e3
Create Date: 2017-08-22 20:30:52.721000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fea657e6c88'
down_revision = 'c8a66ebc33e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saving_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('max_share', sa.Integer(), nullable=True),
    sa.Column('social_fund', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_saving_group_agent_id'), 'saving_group', ['agent_id'], unique=False)
    op.create_index(op.f('ix_saving_group_organization_id'), 'saving_group', ['organization_id'], unique=False)
    op.create_index(op.f('ix_saving_group_project_id'), 'saving_group', ['project_id'], unique=False)
    op.create_index(op.f('ix_saving_group_village_id'), 'saving_group', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saving_group_village_id'), table_name='saving_group')
    op.drop_index(op.f('ix_saving_group_project_id'), table_name='saving_group')
    op.drop_index(op.f('ix_saving_group_organization_id'), table_name='saving_group')
    op.drop_index(op.f('ix_saving_group_agent_id'), table_name='saving_group')
    op.drop_table('saving_group')
    # ### end Alembic commands ###
