"""empty message

Revision ID: 82a9903bb72c
Revises: 775ef3ef4a3d
Create Date: 2017-09-20 23:18:31.819123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a9903bb72c'
down_revision = '775ef3ef4a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('attendance_fine', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_group', 'attendance_fine')
    # ### end Alembic commands ###
