"""empty message

Revision ID: 846705e54583
Revises: f498b791c983
Create Date: 2017-09-18 17:51:51.112229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846705e54583'
down_revision = 'f498b791c983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_social_fund_sg_cycle_id', table_name='member_social_fund')
    op.drop_constraint(u'member_social_fund_sg_cycle_id_fkey', 'member_social_fund', type_='foreignkey')
    op.drop_column('member_social_fund', 'sg_cycle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_social_fund', sa.Column('sg_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_social_fund_sg_cycle_id_fkey', 'member_social_fund', 'sg_cycle', ['sg_cycle_id'], ['id'])
    op.create_index('ix_member_social_fund_sg_cycle_id', 'member_social_fund', ['sg_cycle_id'], unique=False)
    # ### end Alembic commands ###
