"""empty message

Revision ID: 856118a6790d
Revises: bcb113ced4e2
Create Date: 2017-09-11 14:36:55.786928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856118a6790d'
down_revision = 'bcb113ced4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('loan_id', sa.Integer(), nullable=True))
    op.add_column('member_approved_loan', sa.Column('sg_member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_approved_loan_loan_id'), 'member_approved_loan', ['loan_id'], unique=False)
    op.create_index(op.f('ix_member_approved_loan_sg_member_id'), 'member_approved_loan', ['sg_member_id'], unique=False)
    op.drop_index('ix_member_approved_loan_committee_id', table_name='member_approved_loan')
    op.drop_index('ix_member_approved_loan_debit_loan_id', table_name='member_approved_loan')
    op.drop_constraint(u'member_approved_loan_debit_loan_id_fkey', 'member_approved_loan', type_='foreignkey')
    op.drop_constraint(u'member_approved_loan_committee_id_fkey', 'member_approved_loan', type_='foreignkey')
    op.create_foreign_key(None, 'member_approved_loan', 'member_loan', ['loan_id'], ['id'])
    op.create_foreign_key(None, 'member_approved_loan', 'sg_member', ['sg_member_id'], ['id'])
    op.drop_column('member_approved_loan', 'debit_loan_id')
    op.drop_column('member_approved_loan', 'committee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('committee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_approved_loan', sa.Column('debit_loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_approved_loan', type_='foreignkey')
    op.drop_constraint(None, 'member_approved_loan', type_='foreignkey')
    op.create_foreign_key(u'member_approved_loan_committee_id_fkey', 'member_approved_loan', 'sg_member', ['committee_id'], ['id'])
    op.create_foreign_key(u'member_approved_loan_debit_loan_id_fkey', 'member_approved_loan', 'member_loan', ['debit_loan_id'], ['id'])
    op.create_index('ix_member_approved_loan_debit_loan_id', 'member_approved_loan', ['debit_loan_id'], unique=False)
    op.create_index('ix_member_approved_loan_committee_id', 'member_approved_loan', ['committee_id'], unique=False)
    op.drop_index(op.f('ix_member_approved_loan_sg_member_id'), table_name='member_approved_loan')
    op.drop_index(op.f('ix_member_approved_loan_loan_id'), table_name='member_approved_loan')
    op.drop_column('member_approved_loan', 'sg_member_id')
    op.drop_column('member_approved_loan', 'loan_id')
    # ### end Alembic commands ###
