"""empty message

Revision ID: 85f709b5c340
Revises: c669df151792
Create Date: 2017-11-27 16:41:02.480350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f709b5c340'
down_revision = 'c669df151792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_drop_out', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_drop_out_member_id'), 'sg_drop_out', ['member_id'], unique=False)
    op.create_foreign_key(None, 'sg_drop_out', 'sg_member', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_drop_out', type_='foreignkey')
    op.drop_index(op.f('ix_sg_drop_out_member_id'), table_name='sg_drop_out')
    op.drop_column('sg_drop_out', 'member_id')
    # ### end Alembic commands ###
