"""empty message

Revision ID: 8957f86d0243
Revises: 61b0dcf2e9de
Create Date: 2017-09-22 16:50:03.431391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8957f86d0243'
down_revision = '61b0dcf2e9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_fine', 'status')
    # ### end Alembic commands ###
