"""empty message

Revision ID: 8cc2a2cc7663
Revises: 040bce0743f2
Create Date: 2017-12-19 14:12:42.382881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc2a2cc7663'
down_revision = '040bce0743f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member_contributions', sa.Column('external_transaction_id', sa.String(length=30), nullable=True))
    op.add_column('sg_member_contributions', sa.Column('operator_transaction_id', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'sg_member_contributions', ['external_transaction_id'])
    op.create_unique_constraint(None, 'sg_member_contributions', ['operator_transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_member_contributions', type_='unique')
    op.drop_constraint(None, 'sg_member_contributions', type_='unique')
    op.drop_column('sg_member_contributions', 'operator_transaction_id')
    op.drop_column('sg_member_contributions', 'external_transaction_id')
    # ### end Alembic commands ###
