"""empty message

Revision ID: 8cee2fade7b1
Revises: f7194c964f0f
Create Date: 2017-09-07 23:11:25.512435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cee2fade7b1'
down_revision = 'f7194c964f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_loan', 'date_repayment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('date_repayment', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
