"""empty message

Revision ID: 9340e0f60e8f
Revises: b59e3bc2257f
Create Date: 2017-12-19 16:02:07.307478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9340e0f60e8f'
down_revision = 'b59e3bc2257f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('external_transaction_id', sa.String(length=30), nullable=True))
    op.add_column('member_loan', sa.Column('operator_transaction_id', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'member_loan', ['external_transaction_id'])
    op.create_unique_constraint(None, 'member_loan', ['operator_transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_loan', type_='unique')
    op.drop_constraint(None, 'member_loan', type_='unique')
    op.drop_column('member_loan', 'operator_transaction_id')
    op.drop_column('member_loan', 'external_transaction_id')
    # ### end Alembic commands ###
