"""empty message

Revision ID: 9353f678f098
Revises: 9beed1c4c72e
Create Date: 2017-09-18 17:56:59.249432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9353f678f098'
down_revision = '9beed1c4c72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_approved_social_sg_member_id', table_name='member_approved_social')
    op.drop_constraint(u'member_approved_social_sg_member_id_fkey', 'member_approved_social', type_='foreignkey')
    op.drop_column('member_approved_social', 'sg_member_id')
    op.drop_index('ix_member_social_fund_sg_member_id', table_name='member_social_fund')
    op.drop_index('ix_member_social_fund_sg_wallet_id', table_name='member_social_fund')
    op.drop_constraint(u'member_social_fund_sg_member_id_fkey', 'member_social_fund', type_='foreignkey')
    op.drop_constraint(u'member_social_fund_sg_wallet_id_fkey', 'member_social_fund', type_='foreignkey')
    op.drop_column('member_social_fund', 'sg_wallet_id')
    op.drop_column('member_social_fund', 'sg_member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_social_fund', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_social_fund', sa.Column('sg_wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_social_fund_sg_wallet_id_fkey', 'member_social_fund', 'sg_wallet', ['sg_wallet_id'], ['id'])
    op.create_foreign_key(u'member_social_fund_sg_member_id_fkey', 'member_social_fund', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_member_social_fund_sg_wallet_id', 'member_social_fund', ['sg_wallet_id'], unique=False)
    op.create_index('ix_member_social_fund_sg_member_id', 'member_social_fund', ['sg_member_id'], unique=False)
    op.add_column('member_approved_social', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_approved_social_sg_member_id_fkey', 'member_approved_social', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_member_approved_social_sg_member_id', 'member_approved_social', ['sg_member_id'], unique=False)
    # ### end Alembic commands ###
