"""empty message

Revision ID: 97bd35190d6a
Revises: b2197c3c7f62
Create Date: 2017-10-10 15:36:19.165360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bd35190d6a'
down_revision = 'b2197c3c7f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_drop_out', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_drop_out', 'date')
    # ### end Alembic commands ###
