"""empty message

Revision ID: 9beed1c4c72e
Revises: 846705e54583
Create Date: 2017-09-18 17:52:01.986010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9beed1c4c72e'
down_revision = '846705e54583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_social_fund', sa.Column('sg_cycle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_social_fund_sg_cycle_id'), 'member_social_fund', ['sg_cycle_id'], unique=False)
    op.create_foreign_key(None, 'member_social_fund', 'sg_cycle', ['sg_cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_social_fund', type_='foreignkey')
    op.drop_index(op.f('ix_member_social_fund_sg_cycle_id'), table_name='member_social_fund')
    op.drop_column('member_social_fund', 'sg_cycle_id')
    # ### end Alembic commands ###
