"""empty message

Revision ID: 9c60dd40ae11
Revises: 7fea657e6c88
Create Date: 2017-08-30 15:54:51.313919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c60dd40ae11'
down_revision = '7fea657e6c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sg_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_cycle_saving_group_id'), 'sg_cycle', ['saving_group_id'], unique=False)
    op.create_table('sg_fin_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_fin_details_saving_group_id'), 'sg_fin_details', ['saving_group_id'], unique=False)
    op.create_table('sg_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_member_saving_group_id'), 'sg_member', ['saving_group_id'], unique=False)
    op.create_index(op.f('ix_sg_member_user_id'), 'sg_member', ['user_id'], unique=False)
    op.create_table('sg_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_wallet_saving_group_id'), 'sg_wallet', ['saving_group_id'], unique=False)
    op.create_table('sg_debit_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_loaned', sa.Float(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('amount_to_pay', sa.Float(), nullable=True),
    sa.Column('date_repayment', sa.Date(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_debit_loan_sg_cycle_id'), 'sg_debit_loan', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_debit_loan_sg_member_id'), 'sg_debit_loan', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_sg_debit_loan_sg_wallet_id'), 'sg_debit_loan', ['sg_wallet_id'], unique=False)
    op.create_table('sg_drop_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_drop_out_sg_cycle_id'), 'sg_drop_out', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_drop_out_sg_member_id'), 'sg_drop_out', ['sg_member_id'], unique=False)
    op.create_table('sg_member_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('operator', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_member_transaction_sg_cycle_id'), 'sg_member_transaction', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_member_transaction_sg_member_id'), 'sg_member_transaction', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_sg_member_transaction_sg_wallet_id'), 'sg_member_transaction', ['sg_wallet_id'], unique=False)
    op.create_table('sg_social_debit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_debited', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_social_debit_sg_cycle_id'), 'sg_social_debit', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_social_debit_sg_member_id'), 'sg_social_debit', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_sg_social_debit_sg_wallet_id'), 'sg_social_debit', ['sg_wallet_id'], unique=False)
    op.create_table('sg_approved_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('debit_loan_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['debit_loan_id'], ['sg_debit_loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_approved_loan_committee_id'), 'sg_approved_loan', ['committee_id'], unique=False)
    op.create_index(op.f('ix_sg_approved_loan_debit_loan_id'), 'sg_approved_loan', ['debit_loan_id'], unique=False)
    op.create_table('sg_approved_social_debit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('social_debit_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['social_debit_id'], ['sg_social_debit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_approved_social_debit_committee_id'), 'sg_approved_social_debit', ['committee_id'], unique=False)
    op.create_index(op.f('ix_sg_approved_social_debit_social_debit_id'), 'sg_approved_social_debit', ['social_debit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sg_approved_social_debit_social_debit_id'), table_name='sg_approved_social_debit')
    op.drop_index(op.f('ix_sg_approved_social_debit_committee_id'), table_name='sg_approved_social_debit')
    op.drop_table('sg_approved_social_debit')
    op.drop_index(op.f('ix_sg_approved_loan_debit_loan_id'), table_name='sg_approved_loan')
    op.drop_index(op.f('ix_sg_approved_loan_committee_id'), table_name='sg_approved_loan')
    op.drop_table('sg_approved_loan')
    op.drop_index(op.f('ix_sg_social_debit_sg_wallet_id'), table_name='sg_social_debit')
    op.drop_index(op.f('ix_sg_social_debit_sg_member_id'), table_name='sg_social_debit')
    op.drop_index(op.f('ix_sg_social_debit_sg_cycle_id'), table_name='sg_social_debit')
    op.drop_table('sg_social_debit')
    op.drop_index(op.f('ix_sg_member_transaction_sg_wallet_id'), table_name='sg_member_transaction')
    op.drop_index(op.f('ix_sg_member_transaction_sg_member_id'), table_name='sg_member_transaction')
    op.drop_index(op.f('ix_sg_member_transaction_sg_cycle_id'), table_name='sg_member_transaction')
    op.drop_table('sg_member_transaction')
    op.drop_index(op.f('ix_sg_drop_out_sg_member_id'), table_name='sg_drop_out')
    op.drop_index(op.f('ix_sg_drop_out_sg_cycle_id'), table_name='sg_drop_out')
    op.drop_table('sg_drop_out')
    op.drop_index(op.f('ix_sg_debit_loan_sg_wallet_id'), table_name='sg_debit_loan')
    op.drop_index(op.f('ix_sg_debit_loan_sg_member_id'), table_name='sg_debit_loan')
    op.drop_index(op.f('ix_sg_debit_loan_sg_cycle_id'), table_name='sg_debit_loan')
    op.drop_table('sg_debit_loan')
    op.drop_index(op.f('ix_sg_wallet_saving_group_id'), table_name='sg_wallet')
    op.drop_table('sg_wallet')
    op.drop_index(op.f('ix_sg_member_user_id'), table_name='sg_member')
    op.drop_index(op.f('ix_sg_member_saving_group_id'), table_name='sg_member')
    op.drop_table('sg_member')
    op.drop_index(op.f('ix_sg_fin_details_saving_group_id'), table_name='sg_fin_details')
    op.drop_table('sg_fin_details')
    op.drop_index(op.f('ix_sg_cycle_saving_group_id'), table_name='sg_cycle')
    op.drop_table('sg_cycle')
    # ### end Alembic commands ###
