"""empty message

Revision ID: a0fe67c4b587
Revises: 7288ef1f6458
Create Date: 2017-09-22 16:07:28.901770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fe67c4b587'
down_revision = '7288ef1f6458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_fine_wallet_id'), 'member_fine', ['wallet_id'], unique=False)
    op.create_foreign_key(None, 'member_fine', 'sg_wallet', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_fine', type_='foreignkey')
    op.drop_index(op.f('ix_member_fine_wallet_id'), table_name='member_fine')
    op.drop_column('member_fine', 'wallet_id')
    # ### end Alembic commands ###
