"""empty message

Revision ID: a73f4e455976
Revises: 5c5ee9e52fea
Create Date: 2017-11-20 16:47:58.221292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73f4e455976'
down_revision = '5c5ee9e52fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_loan_repayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['member_loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_loan_repayment_loan_id'), 'member_loan_repayment', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_loan_repayment_loan_id'), table_name='member_loan_repayment')
    op.drop_table('member_loan_repayment')
    # ### end Alembic commands ###
