"""empty message

Revision ID: adf75110ea41
Revises: 6284e780abb4
Create Date: 2018-01-03 13:08:05.970291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf75110ea41'
down_revision = '6284e780abb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_share_out', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_share_out', 'status')
    # ### end Alembic commands ###
