"""empty message

Revision ID: b8d0b19e9445
Revises: f921d83619fd
Create Date: 2017-12-26 18:22:03.838075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d0b19e9445'
down_revision = 'f921d83619fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_fine_repayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=30), nullable=True),
    sa.Column('operator_transaction_id', sa.String(length=30), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['member_loan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id'),
    sa.UniqueConstraint('operator_transaction_id')
    )
    op.create_index(op.f('ix_member_fine_repayment_loan_id'), 'member_fine_repayment', ['loan_id'], unique=False)
    op.add_column(u'sg_share_out', sa.Column('initiator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_share_out_initiator_id'), 'sg_share_out', ['initiator_id'], unique=False)
    op.create_foreign_key(None, 'sg_share_out', 'sg_member', ['initiator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_share_out', type_='foreignkey')
    op.drop_index(op.f('ix_sg_share_out_initiator_id'), table_name='sg_share_out')
    op.drop_column(u'sg_share_out', 'initiator_id')
    op.drop_index(op.f('ix_member_fine_repayment_loan_id'), table_name='member_fine_repayment')
    op.drop_table('member_fine_repayment')
    # ### end Alembic commands ###
