"""empty message

Revision ID: bcb113ced4e2
Revises: 7ddff9ce6478
Create Date: 2017-09-11 12:55:37.736199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb113ced4e2'
down_revision = '7ddff9ce6478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_member', 'admin')
    # ### end Alembic commands ###
