"""empty message

Revision ID: c0698715bde1
Revises: 7a0310ae7b18
Create Date: 2017-08-30 22:38:49.167686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0698715bde1'
down_revision = '7a0310ae7b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('creation_date', sa.Date(), nullable=True))
    op.drop_column('saving_group', 'reg_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('reg_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('saving_group', 'creation_date')
    # ### end Alembic commands ###
