"""empty message

Revision ID: c3f396094041
Revises: e6e8437bfd43
Create Date: 2017-12-17 22:50:52.973010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f396094041'
down_revision = 'e6e8437bfd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_meeting', sa.Column('property_at_cycle_start', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sg_meeting', 'property_at_cycle_start')
    # ### end Alembic commands ###
