"""empty message

Revision ID: c4ee3f404101
Revises: 0993e072ea55
Create Date: 2017-12-14 19:04:10.883702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ee3f404101'
down_revision = '0993e072ea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'saving_group_village_id_fkey', 'saving_group', type_='foreignkey')
    op.add_column('sg_member', sa.Column('village_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_member_village_id'), 'sg_member', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sg_member_village_id'), table_name='sg_member')
    op.drop_column('sg_member', 'village_id')
    op.create_foreign_key(u'saving_group_village_id_fkey', 'saving_group', 'village', ['village_id'], ['id'])
    # ### end Alembic commands ###
