"""empty message

Revision ID: c669df151792
Revises: 6a2ad52f7e77
Create Date: 2017-11-27 16:39:32.701070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c669df151792'
down_revision = '6a2ad52f7e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_drop_out_sg_member_id', table_name='sg_drop_out')
    op.drop_constraint(u'sg_drop_out_sg_member_id_fkey', 'sg_drop_out', type_='foreignkey')
    op.drop_column('sg_drop_out', 'sg_member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_drop_out', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sg_drop_out_sg_member_id_fkey', 'sg_drop_out', 'sg_member', ['sg_member_id'], ['id'])
    op.create_index('ix_sg_drop_out_sg_member_id', 'sg_drop_out', ['sg_member_id'], unique=False)
    # ### end Alembic commands ###
