"""empty message

Revision ID: c8a66ebc33e3
Revises: 3497d3f0a753
Create Date: 2017-08-22 15:59:28.399037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a66ebc33e3'
down_revision = '3497d3f0a753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('project_agent_index', 'project_agent', ['project_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('project_agent_index', table_name='project_agent')
    # ### end Alembic commands ###
