"""empty message

Revision ID: cabb0df3988a
Revises: 03dc3ba21822
Create Date: 2017-12-10 16:07:59.266451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabb0df3988a'
down_revision = '03dc3ba21822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key')
    # ### end Alembic commands ###
