"""empty message

Revision ID: cde8b0e2e30b
Revises: ce57fc79d777
Create Date: 2017-10-06 11:44:06.846885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde8b0e2e30b'
down_revision = 'ce57fc79d777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members_mini_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['sg_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_mini_statement_member_id'), 'members_mini_statement', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_mini_statement_member_id'), table_name='members_mini_statement')
    op.drop_table('members_mini_statement')
    # ### end Alembic commands ###
