"""empty message

Revision ID: ce57fc79d777
Revises: 5db7cecdc467
Create Date: 2017-10-03 15:11:04.445335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce57fc79d777'
down_revision = '5db7cecdc467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_social', sa.Column('sg_member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_approved_social_sg_member_id'), 'member_approved_social', ['sg_member_id'], unique=False)
    op.create_foreign_key(None, 'member_approved_social', 'sg_member', ['sg_member_id'], ['id'])
    op.add_column('member_fine', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_fine_member_id'), 'member_fine', ['member_id'], unique=False)
    op.create_foreign_key(None, 'member_fine', 'sg_member', ['member_id'], ['id'])
    op.add_column('member_social_fund', sa.Column('sg_member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_social_fund_sg_member_id'), 'member_social_fund', ['sg_member_id'], unique=False)
    op.create_foreign_key(None, 'member_social_fund', 'sg_member', ['sg_member_id'], ['id'])
    op.add_column('sg_member_contributions', sa.Column('sg_member_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sg_member_contributions_sg_member_id'), 'sg_member_contributions', ['sg_member_id'], unique=False)
    op.create_foreign_key(None, 'sg_member_contributions', 'sg_member', ['sg_member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sg_member_contributions', type_='foreignkey')
    op.drop_index(op.f('ix_sg_member_contributions_sg_member_id'), table_name='sg_member_contributions')
    op.drop_column('sg_member_contributions', 'sg_member_id')
    op.drop_constraint(None, 'member_social_fund', type_='foreignkey')
    op.drop_index(op.f('ix_member_social_fund_sg_member_id'), table_name='member_social_fund')
    op.drop_column('member_social_fund', 'sg_member_id')
    op.drop_constraint(None, 'member_fine', type_='foreignkey')
    op.drop_index(op.f('ix_member_fine_member_id'), table_name='member_fine')
    op.drop_column('member_fine', 'member_id')
    op.drop_constraint(None, 'member_approved_social', type_='foreignkey')
    op.drop_index(op.f('ix_member_approved_social_sg_member_id'), table_name='member_approved_social')
    op.drop_column('member_approved_social', 'sg_member_id')
    # ### end Alembic commands ###
