"""empty message

Revision ID: d22807e973db
Revises: b40d7c773ca6
Create Date: 2017-08-08 12:26:29.235608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22807e973db'
down_revision = 'b40d7c773ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('organization', 'country_code')
    op.add_column('users', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'date')
    op.add_column('organization', sa.Column('country_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('organization', 'date')
    # ### end Alembic commands ###
