"""empty message

Revision ID: d26c672fb6aa
Revises: adf75110ea41
Create Date: 2018-01-04 00:16:17.468996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26c672fb6aa'
down_revision = 'adf75110ea41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_out_share_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=30), nullable=True),
    sa.Column('operator_transaction_id', sa.String(length=30), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('drop_out_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drop_out_id'], ['sg_drop_out.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['sg_member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id'),
    sa.UniqueConstraint('operator_transaction_id')
    )
    op.create_index(op.f('ix_drop_out_share_out_drop_out_id'), 'drop_out_share_out', ['drop_out_id'], unique=False)
    op.create_index(op.f('ix_drop_out_share_out_member_id'), 'drop_out_share_out', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drop_out_share_out_member_id'), table_name='drop_out_share_out')
    op.drop_index(op.f('ix_drop_out_share_out_drop_out_id'), table_name='drop_out_share_out')
    op.drop_table('drop_out_share_out')
    # ### end Alembic commands ###
