"""empty message

Revision ID: d50b3b510f98
Revises: a0fe67c4b587
Create Date: 2017-09-22 16:10:50.054526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50b3b510f98'
down_revision = 'a0fe67c4b587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_fine_cycle_id'), 'member_fine', ['cycle_id'], unique=False)
    op.create_foreign_key(None, 'member_fine', 'sg_cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_fine', type_='foreignkey')
    op.drop_index(op.f('ix_member_fine_cycle_id'), table_name='member_fine')
    op.drop_column('member_fine', 'cycle_id')
    # ### end Alembic commands ###
