"""empty message

Revision ID: d93e2e4a8a3d
Revises: a73f4e455976
Create Date: 2017-11-23 17:05:50.619742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93e2e4a8a3d'
down_revision = 'a73f4e455976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_group', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_group', 'date')
    # ### end Alembic commands ###
