"""empty message

Revision ID: dacb1dcf4663
Revises: ea76d41e061f
Create Date: 2017-11-20 13:03:14.050970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb1dcf4663'
down_revision = 'ea76d41e061f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('sg_fine_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_fine_initiate_by'), 'member_fine', ['initiate_by'], unique=False)
    op.create_index(op.f('ix_member_fine_sg_fine_id'), 'member_fine', ['sg_fine_id'], unique=False)
    op.drop_index('ix_member_fine_cycle_id', table_name='member_fine')
    op.drop_constraint(u'member_fine_cycle_id_fkey', 'member_fine', type_='foreignkey')
    op.create_foreign_key(None, 'member_fine', 'sg_fines', ['sg_fine_id'], ['id'])
    op.drop_column('member_fine', 'cycle_id')
    op.drop_column('member_fine', 'type')
    op.drop_column('member_fine', 'amount')
    op.add_column('sg_fines', sa.Column('fine', sa.Integer(), nullable=True))
    op.add_column('sg_fines', sa.Column('fine_type', sa.Integer(), nullable=True))
    op.add_column('sg_fines', sa.Column('name', sa.String(length=40), nullable=True))
    op.drop_column('sg_fines', 'meeting')
    op.drop_column('sg_fines', 'social_fund')
    op.drop_column('sg_fines', 'attendance')
    op.drop_column('sg_fines', 'saving')
    op.drop_column('sg_fines', 'loan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_fines', sa.Column('loan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sg_fines', sa.Column('saving', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sg_fines', sa.Column('attendance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sg_fines', sa.Column('social_fund', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sg_fines', sa.Column('meeting', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sg_fines', 'name')
    op.drop_column('sg_fines', 'fine_type')
    op.drop_column('sg_fines', 'fine')
    op.add_column('member_fine', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_fine', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('member_fine', sa.Column('cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_fine', type_='foreignkey')
    op.create_foreign_key(u'member_fine_cycle_id_fkey', 'member_fine', 'sg_cycle', ['cycle_id'], ['id'])
    op.create_index('ix_member_fine_cycle_id', 'member_fine', ['cycle_id'], unique=False)
    op.drop_index(op.f('ix_member_fine_sg_fine_id'), table_name='member_fine')
    op.drop_index(op.f('ix_member_fine_initiate_by'), table_name='member_fine')
    op.drop_column('member_fine', 'sg_fine_id')
    # ### end Alembic commands ###
