"""empty message

Revision ID: dba3b1bec62d
Revises: 42eccb7328c3
Create Date: 2017-10-28 22:59:37.393712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba3b1bec62d'
down_revision = '42eccb7328c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sg_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('saving_group_id', sa.Integer(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['saving_group_id'], ['saving_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_meeting_cycle_id'), 'sg_meeting', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_meeting_saving_group_id'), 'sg_meeting', ['saving_group_id'], unique=False)
    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sg_meeting_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_meeting_id'], ['sg_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_attendance_member_id'), 'meeting_attendance', ['member_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendance_sg_meeting_id'), 'meeting_attendance', ['sg_meeting_id'], unique=False)
    op.create_index('unique_attendee', 'meeting_attendance', ['sg_meeting_id', 'member_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_attendee', table_name='meeting_attendance')
    op.drop_index(op.f('ix_meeting_attendance_sg_meeting_id'), table_name='meeting_attendance')
    op.drop_index(op.f('ix_meeting_attendance_member_id'), table_name='meeting_attendance')
    op.drop_table('meeting_attendance')
    op.drop_index(op.f('ix_sg_meeting_saving_group_id'), table_name='sg_meeting')
    op.drop_index(op.f('ix_sg_meeting_cycle_id'), table_name='sg_meeting')
    op.drop_table('sg_meeting')
    # ### end Alembic commands ###
