"""empty message

Revision ID: ddf1dfecc4be
Revises: 734f9e2e2f58
Create Date: 2017-09-04 16:55:21.959374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf1dfecc4be'
down_revision = '734f9e2e2f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sg_member_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('operator', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sg_cycle_id', sa.Integer(), nullable=True),
    sa.Column('sg_member_id', sa.Integer(), nullable=True),
    sa.Column('sg_wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], ['sg_cycle.id'], ),
    sa.ForeignKeyConstraint(['sg_member_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['sg_wallet_id'], ['sg_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sg_member_contributions_sg_cycle_id'), 'sg_member_contributions', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_sg_member_contributions_sg_member_id'), 'sg_member_contributions', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_sg_member_contributions_sg_wallet_id'), 'sg_member_contributions', ['sg_wallet_id'], unique=False)
    op.drop_table('sg_member_transaction')
    op.add_column('sg_cycle', sa.Column('active', sa.Integer(), nullable=True))
    op.create_index('unique_cycle', 'sg_cycle', ['start', 'end', 'saving_group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_cycle', table_name='sg_cycle')
    op.drop_column('sg_cycle', 'active')
    op.create_table('sg_member_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operator', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sg_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_wallet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sg_cycle_id'], [u'sg_cycle.id'], name=u'sg_member_transaction_sg_cycle_id_fkey'),
    sa.ForeignKeyConstraint(['sg_member_id'], [u'sg_member.id'], name=u'sg_member_transaction_sg_member_id_fkey'),
    sa.ForeignKeyConstraint(['sg_wallet_id'], [u'sg_wallet.id'], name=u'sg_member_transaction_sg_wallet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'sg_member_transaction_pkey')
    )
    op.drop_index(op.f('ix_sg_member_contributions_sg_wallet_id'), table_name='sg_member_contributions')
    op.drop_index(op.f('ix_sg_member_contributions_sg_member_id'), table_name='sg_member_contributions')
    op.drop_index(op.f('ix_sg_member_contributions_sg_cycle_id'), table_name='sg_member_contributions')
    op.drop_table('sg_member_contributions')
    # ### end Alembic commands ###
