"""empty message

Revision ID: def50d3996d6
Revises: c0698715bde1
Create Date: 2017-08-31 11:08:49.132049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def50d3996d6'
down_revision = 'c0698715bde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_member_saving_group_id', table_name='sg_member')
    op.drop_constraint(u'sg_member_saving_group_id_fkey', 'sg_member', type_='foreignkey')
    op.drop_column('sg_member', 'saving_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('saving_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'sg_member_saving_group_id_fkey', 'sg_member', 'saving_group', ['saving_group_id'], ['id'])
    op.create_index('ix_sg_member_saving_group_id', 'sg_member', ['saving_group_id'], unique=False)
    # ### end Alembic commands ###
