"""empty message

Revision ID: e21b0ecc11e8
Revises: 04c08b9dcee6
Create Date: 2017-12-26 06:44:02.459214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21b0ecc11e8'
down_revision = '04c08b9dcee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_write_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['member_loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_write_off_admin_id'), 'member_write_off', ['admin_id'], unique=False)
    op.create_index(op.f('ix_member_write_off_loan_id'), 'member_write_off', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_write_off_loan_id'), table_name='member_write_off')
    op.drop_index(op.f('ix_member_write_off_admin_id'), table_name='member_write_off')
    op.drop_table('member_write_off')
    # ### end Alembic commands ###
