"""empty message

Revision ID: e6e8437bfd43
Revises: c4ee3f404101
Create Date: 2017-12-14 22:16:21.069108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e8437bfd43'
down_revision = 'c4ee3f404101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sg_member_village_id', table_name='sg_member')
    op.drop_column('sg_member', 'village_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_member', sa.Column('village_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_sg_member_village_id', 'sg_member', ['village_id'], unique=False)
    # ### end Alembic commands ###
