"""empty message

Revision ID: e9c75a401f34
Revises: d22807e973db
Create Date: 2017-08-08 15:57:50.624445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c75a401f34'
down_revision = 'd22807e973db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'phone')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.add_column('organization', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
