"""empty message

Revision ID: ea76d41e061f
Revises: dba3b1bec62d
Create Date: 2017-11-19 18:42:28.717217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea76d41e061f'
down_revision = 'dba3b1bec62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sg_meeting', sa.Column('bank_balance', sa.Integer(), nullable=True))
    op.add_column('sg_meeting', sa.Column('external_debt', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_constraint(u'users_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_phone_key', 'users', ['phone'])
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('sg_meeting', 'external_debt')
    op.drop_column('sg_meeting', 'bank_balance')
    # ### end Alembic commands ###
