"""empty message

Revision ID: eb11014c3709
Revises: 82243f9906ea
Create Date: 2017-09-07 23:01:44.017210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb11014c3709'
down_revision = '82243f9906ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_loan_sg_cycle_id', table_name='member_loan')
    op.drop_index('ix_member_loan_sg_member_id', table_name='member_loan')
    op.drop_index('ix_member_loan_sg_wallet_id', table_name='member_loan')
    op.drop_constraint(u'member_loan_sg_wallet_id_fkey', 'member_loan', type_='foreignkey')
    op.drop_constraint(u'member_loan_sg_member_id_fkey', 'member_loan', type_='foreignkey')
    op.drop_constraint(u'member_loan_sg_cycle_id_fkey', 'member_loan', type_='foreignkey')
    op.drop_column('member_loan', 'sg_wallet_id')
    op.drop_column('member_loan', 'sg_cycle_id')
    op.drop_column('member_loan', 'sg_member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('sg_member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_loan', sa.Column('sg_cycle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member_loan', sa.Column('sg_wallet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_loan_sg_cycle_id_fkey', 'member_loan', 'sg_cycle', ['sg_cycle_id'], ['id'])
    op.create_foreign_key(u'member_loan_sg_member_id_fkey', 'member_loan', 'sg_member', ['sg_member_id'], ['id'])
    op.create_foreign_key(u'member_loan_sg_wallet_id_fkey', 'member_loan', 'sg_wallet', ['sg_wallet_id'], ['id'])
    op.create_index('ix_member_loan_sg_wallet_id', 'member_loan', ['sg_wallet_id'], unique=False)
    op.create_index('ix_member_loan_sg_member_id', 'member_loan', ['sg_member_id'], unique=False)
    op.create_index('ix_member_loan_sg_cycle_id', 'member_loan', ['sg_cycle_id'], unique=False)
    # ### end Alembic commands ###
