"""empty message

Revision ID: ec1cd32ef1fd
Revises: 088c5c66de80
Create Date: 2017-09-07 22:10:28.523577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1cd32ef1fd'
down_revision = '088c5c66de80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_approved_loan_debit_loan_id', table_name='member_approved_loan')
    op.drop_constraint(u'member_approved_loan_debit_loan_id_fkey', 'member_approved_loan', type_='foreignkey')
    op.drop_column('member_approved_loan', 'debit_loan_id')
    op.drop_index('ix_member_approved_social_social_debit_id', table_name='member_approved_social')
    op.drop_constraint(u'member_approved_social_social_debit_id_fkey', 'member_approved_social', type_='foreignkey')
    op.drop_column('member_approved_social', 'social_debit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_social', sa.Column('social_debit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_approved_social_social_debit_id_fkey', 'member_approved_social', 'member_social_fund', ['social_debit_id'], ['id'])
    op.create_index('ix_member_approved_social_social_debit_id', 'member_approved_social', ['social_debit_id'], unique=False)
    op.add_column('member_approved_loan', sa.Column('debit_loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'member_approved_loan_debit_loan_id_fkey', 'member_approved_loan', 'member_loan', ['debit_loan_id'], ['id'])
    op.create_index('ix_member_approved_loan_debit_loan_id', 'member_approved_loan', ['debit_loan_id'], unique=False)
    # ### end Alembic commands ###
