"""empty message

Revision ID: ed2178f487c8
Revises: 774412da8464
Create Date: 2017-12-23 12:23:33.792888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2178f487c8'
down_revision = '774412da8464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan_repayment', sa.Column('external_transaction_id', sa.String(length=30), nullable=True))
    op.add_column('member_loan_repayment', sa.Column('operator_transaction_id', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'member_loan_repayment', ['external_transaction_id'])
    op.create_unique_constraint(None, 'member_loan_repayment', ['operator_transaction_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_loan_repayment', type_='unique')
    op.drop_constraint(None, 'member_loan_repayment', type_='unique')
    op.drop_column('member_loan_repayment', 'operator_transaction_id')
    op.drop_column('member_loan_repayment', 'external_transaction_id')
    # ### end Alembic commands ###
