"""empty message

Revision ID: ee80a15ad815
Revises: 7a69031a4a7d
Create Date: 2018-01-12 00:32:15.702835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee80a15ad815'
down_revision = '7a69031a4a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key')
    # ### end Alembic commands ###
