"""empty message

Revision ID: f498b791c983
Revises: 99d5cb2ed427
Create Date: 2017-09-18 17:46:41.353179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f498b791c983'
down_revision = '99d5cb2ed427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_social_fund', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('member_social_fund', 'amount_debited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_social_fund', sa.Column('amount_debited', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('member_social_fund', 'amount')
    # ### end Alembic commands ###
