"""empty message

Revision ID: f635efb380b5
Revises: 002dba70db49
Create Date: 2017-09-24 22:00:48.354897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f635efb380b5'
down_revision = '002dba70db49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_fine', sa.Column('type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_fine', 'type')
    # ### end Alembic commands ###
