"""empty message

Revision ID: f7194c964f0f
Revises: eb11014c3709
Create Date: 2017-09-07 23:02:02.292338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7194c964f0f'
down_revision = 'eb11014c3709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('sg_cycle_id', sa.Integer(), nullable=True))
    op.add_column('member_loan', sa.Column('sg_member_id', sa.Integer(), nullable=True))
    op.add_column('member_loan', sa.Column('sg_wallet_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_member_loan_sg_cycle_id'), 'member_loan', ['sg_cycle_id'], unique=False)
    op.create_index(op.f('ix_member_loan_sg_member_id'), 'member_loan', ['sg_member_id'], unique=False)
    op.create_index(op.f('ix_member_loan_sg_wallet_id'), 'member_loan', ['sg_wallet_id'], unique=False)
    op.create_foreign_key(None, 'member_loan', 'sg_wallet', ['sg_wallet_id'], ['id'])
    op.create_foreign_key(None, 'member_loan', 'sg_cycle', ['sg_cycle_id'], ['id'])
    op.create_foreign_key(None, 'member_loan', 'sg_member', ['sg_member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member_loan', type_='foreignkey')
    op.drop_constraint(None, 'member_loan', type_='foreignkey')
    op.drop_constraint(None, 'member_loan', type_='foreignkey')
    op.drop_index(op.f('ix_member_loan_sg_wallet_id'), table_name='member_loan')
    op.drop_index(op.f('ix_member_loan_sg_member_id'), table_name='member_loan')
    op.drop_index(op.f('ix_member_loan_sg_cycle_id'), table_name='member_loan')
    op.drop_column('member_loan', 'sg_wallet_id')
    op.drop_column('member_loan', 'sg_member_id')
    op.drop_column('member_loan', 'sg_cycle_id')
    # ### end Alembic commands ###
