"""empty message

Revision ID: f762d968c259
Revises: 7306b05cb99f
Create Date: 2017-09-12 11:43:13.978429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f762d968c259'
down_revision = '7306b05cb99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_approved_loan', sa.Column('approve_date', sa.DateTime(), nullable=True))
    op.add_column('member_approved_loan', sa.Column('declined_date', sa.DateTime(), nullable=True))
    op.drop_column('member_loan', 'approve_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_loan', sa.Column('approve_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('member_approved_loan', 'declined_date')
    op.drop_column('member_approved_loan', 'approve_date')
    # ### end Alembic commands ###
