"""empty message

Revision ID: f81c1eda135d
Revises: 6c88fdefeadf
Create Date: 2017-09-11 17:12:14.114575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81c1eda135d'
down_revision = '6c88fdefeadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmation_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
