"""empty message

Revision ID: f921d83619fd
Revises: 7b819cd1e068
Create Date: 2017-12-26 08:24:54.433272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f921d83619fd'
down_revision = '7b819cd1e068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_share_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('share_out_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['sg_member.id'], ),
    sa.ForeignKeyConstraint(['share_out_id'], ['sg_share_out.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approved_share_out_admin_id'), 'approved_share_out', ['admin_id'], unique=False)
    op.create_index(op.f('ix_approved_share_out_share_out_id'), 'approved_share_out', ['share_out_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approved_share_out_share_out_id'), table_name='approved_share_out')
    op.drop_index(op.f('ix_approved_share_out_admin_id'), table_name='approved_share_out')
    op.drop_table('approved_share_out')
    # ### end Alembic commands ###
