"""empty message

Revision ID: fc219b8e064f
Revises: c33b9f8ed078
Create Date: 2017-08-09 12:26:32.407504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc219b8e064f'
down_revision = 'c33b9f8ed078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_organization_id'), 'project', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'project', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_index(op.f('ix_project_organization_id'), table_name='project')
    op.drop_column('project', 'organization_id')
    # ### end Alembic commands ###
